# Generated by Django 5.0.4 on 2024-04-08 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Examen_medical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_rapport",
                    models.CharField(
                        default="", max_length=1000, verbose_name="type de rapport"
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rapport_medical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "motif_consultation",
                    models.CharField(
                        max_length=1000,
                        null=True,
                        verbose_name="motif de la consultation",
                    ),
                ),
                (
                    "traitement_prescrit",
                    models.CharField(
                        max_length=1000, null=True, verbose_name="traitement prescrits"
                    ),
                ),
                ("recommandation", models.CharField(max_length=2000, null=True)),
                ("date_consultation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateField(auto_now=True)),
                (
                    "examen_medical",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.examen_medical",
                    ),
                ),
                (
                    "medecin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
