# Generated by Django 5.0.4 on 2024-04-11 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hospitalisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_hospitalisation", models.DateTimeField(auto_now_add=True)),
                (
                    "motif",
                    models.CharField(
                        max_length=1000, null=True, verbose_name="motif hospitalisation"
                    ),
                ),
                (
                    "numero_de_chambre",
                    models.CharField(
                        max_length=100, null=True, verbose_name="numero de chambre"
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                (
                    "medecin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medecin_responsable",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="medecin responsable",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_conserne",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
