# Generated by Django 5.0.4 on 2024-04-11 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0002_hospitalisation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_medicament",
                    models.CharField(
                        max_length=100, null=True, verbose_name="nom du medicament"
                    ),
                ),
                ("Dosage", models.IntegerField(null=True)),
                (
                    "forme_pharmaceutique",
                    models.CharField(
                        choices=[
                            ("COMPRIME", "comprimés"),
                            ("GELULES", "gélules"),
                            ("SIROP", "sirop"),
                            ("AUTRES", "autres"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("Posologie", models.CharField(max_length=1000, null=True)),
                (
                    "dure_traitement",
                    models.DateField(
                        auto_now_add=True, verbose_name="Duree du traitement en jours"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ordonnance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_prescription",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date prescription"
                    ),
                ),
                (
                    "medecin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medecin_prescripteur",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medicament_prescrits",
                    models.ForeignKey(
                        max_length=1000,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.medicament",
                        verbose_name="medicaments prescrits",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_beneficaire",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
