# Generated by Django 5.0.4 on 2024-04-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0003_medicament_ordonnance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicament",
            name="dure_traitement",
            field=models.DateField(verbose_name="Duree du traitement en jours"),
        ),
    ]
