# Generated by Django 5.0.4 on 2024-04-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_naissance",
            field=models.DateField(null=True),
        ),
    ]
